### ISSUE TITLE
Question about stock / customized firmware

### ISSUE THREAD

**Issue by kemp-dev** [stich86/UF-Instant-Mod#1]
I have some  questions about the different firmware versions.
If I have stock firmware v4.4.2.1248-550.220304.1317 installed, and I use commands like:
`flash set GPON_SN YOURSN
flash set OMCI_FAKE_OK 1
flash set OMCI_OLT_MODE 1
flash set PON_VENDOR_ID HWTC`

... then this will not work because of the vendorlock, so we need to install the modified root FS to support OLT's like Huawei.
Is this correct?

And can we use firmware v4.4.2.1248-550.220304.1317 with the modified root FS, or do we need to first install v4.3.1.913-d48.210415.0811?

**Comment by stich86** [comment]
Hi @kemp-dev

Stock firmare doesn't support that command because it's vendor locking on UFiber.

The mod is just on rootFS that has omci_app form VSOL V2801F. An universal ONU GPON SFP.

You can also use firmware 4.4, you will replace only rootFS, kernel will be from original Ubiquiti firmare (for laser interface)

**Comment by jjeziorny** [comment]
How about older firmware? My SFP is currently running 4.1, is it likely that your modified rootFS will work fine with this older version?

If not, how can the firmware be updated, does it need UART or is there an easier approach? 

Might need to update it anyway as there's no nc on my version of the firmware.

**Comment by kemp-dev** [comment]
In /etc/scripts there is a firmware update script which you can use to update stock firmware.
You'll need to get the new firmware in /tmp and then you can update the firmware for the image that is not active.

I was able to SSH, so I could use SCP (winscp) to upload the firmware to /tmp.

**Comment by jjeziorny** [comment]
Thanks for the comments, after having to fiddle around to copy the firmware file as scp wouldn't work I got it updated and patched. I'll leave the command I used for copying it here in case it helps someone else.
`tar -c UF-INSTANT.v4.3.1.913-d48.210415.0811.img | ssh ubnt@192.168.1.1 tar -x -C /tmp/`

So, applied my SN and SLID and got it working with my provider fine.

There is one little annoyance thou, since the upgrade I lost SSH to the SFP and can only access via telnet. It seems dropbear is not available.

You mean in the modded one?
If so... yes, only telnet because dropbear doesn't work on V2801F firmware :(

yes in the modded. no worries, I can live without it

**Comment by kemp-dev** [comment]
Yeah, I also noticed this. With telnet, it is a bit more work to transfer files. SSH would be a nice to have :)
...but anyway, it is working fine over here. I replaced my prodiver's Huawei for the Ufiber in a UDM SE.

Another odd thing I noticed is that the SFP port adds an extra 1ms latency, compared to the WAN ethernet port. Maybe a Unifi thing?

**Comment by stich86** [comment]
very strange, usually it's just a bridge

**Comment by kemp-dev** [comment]
I did some more tests. This 1ms latency is not coming from the SFP, the extra latency is somewhere in my providers network, but only when using your own ONU. Maybe some extra security rules if they detect odd devices or something like that.
I could clone all settings so it looks the same, but that's not worth it for now.
